# conda env create -f dev-environment.yml
name: lume-epics-dev
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pcaspy
  - p4p
  - pyepics
  - numpy
  - bokeh
  - click
  - pyyaml
  - lume-model>=1.4
  - nose>=1.1.2

  # dev requirements
  - pre-commit
  - doctr
  - black
  - pytest

  # docs requirements
  - mkdocs
  - mkdocstrings
  - mkdocstrings-python
  - mkdocs-material
