# conda env create -f environment.yml
name: lume-epics
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pcaspy
  - p4p
  - pyepics
  - numpy
  - bokeh
  - click
  - pyyaml
  - lume-model>=1.4
  - nose>=1.1.2
