site_name: lume-epics
site_url: https://slaclab.github.io/lume-epics
repo_url: https://github.com/slaclab/lume-epics
nav:
  - Overview: index.md
  - Install: Install.md
  - Tutorial:
    - Bokeh Server: BokehServer.md
  - Widgets: Widgets_doc.md
  - API:
    - Client:
      - Controller: Controller.md
      - Monitors: Monitors.md
      - Widgets: Widgets.md
    - Model: Model.md
    - Server: Server.md
    - EPICS: EPICS.md
plugins:
  - search:
      separator: '[\s\-\.]'
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            inherited_members: false
            filters:
              - "!^_"  # exlude all members starting with _
              - "^__init__$"  # but always include __init__ modules and methods
          rendering:
            show_source: true
            show_root_toc_entry: false
            show_root_heading: true
            show_if_no_docstring: false
            show_signature_annotations: true
            separate_signature: true
            merge_init_into_class: true
            show_submodules: true
            heading_level: 2

theme:
  name: material
  features:
    - toc.integrate
    - toc.follow
    - navigation.top
    - navigation.tabs
