{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: "lume-epics"
  version: {{ data.get('version') }}
build:
  noarch: python
  number: 0

source:
  path: ..

requirements:
  host:
    - python >=3.6
    - setuptools
  run:
    - python >=3.6
    - epics-base
    - pyepics
    - pcaspy
    - p4p
    - numpy
    - bokeh>=2.3.3
    - click
    - lume-model>=0.13
    - nose>=1.1.2

test:
  imports:
    - lume_epics
  requires:
    - pytest
  commands:
    - py.test --pyargs lume_epics

about:
  home: https://github.com/slaclab/lume-epics
  license: SLAC Open
  license_family: OTHER
  license_file: LICENSE
  summary: Lume-epics is a dedicated API for serving LUME model variables with EPICS.
  doc_url: https://slaclab.github.io/lume-epics/
  dev_url: https://github.com/slaclab/lume-epics
