input_variables:
  input1:
    pvname: test:input1
    protocol: ca

  input2:
    pvname: test:input2
    protocol: pva

output_variables:
  output_summary:
    pvname: test:output_summary
    protocol: pva
    fields:
      - output1
      - output2
      - output3
