name: Build lume-epics

on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]

    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          auto-activate-base: false
          activate-environment: lume-epics
          environment-file: environment.yml
          channels: conda-forge
          channel-priority: strict
          python-version: ${{ matrix.python-version }}
      - name: Install build
        run: |
          python -m pip install build --user
      - name: Build a source tarball
        run: |
          python -m build
