
name: Build Docs

on:
  push:
    branches:
      - main
      - github-actions
jobs:
  build:
    if: ${{ github.repository == 'slaclab/lume-epics' }}
    runs-on: ubuntu-latest
    name:  Build Docs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          auto-activate-base: false
          activate-environment: lume-epics-dev
          environment-file: dev-environment.yml
          channels: conda-forge
          python-version: "3.10"
      - name: Build Docs
        shell: bash -l {0}
        run: |
          mkdocs build
          mkdocs gh-deploy --force
