name: Build lume-epics

on:
  push:
    branches:    
      - master
      - github-actions
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.7, 3.8]
    name: Python ${{ matrix.python-version }}, ${{ matrix.os }} build
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: true
          conda-build-version: 3.18.11
          python-version: ${{ matrix.python-version }}
          channels: anaconda,conda-forge
          channel-priority: flexible
      - name: Build package
        run: |
          conda build -q conda-recipe --python=${{ matrix.python-version }} --output-folder bld-dir
