name: Build lume-epics

on:
  push:
    branches:
      - main
      - github-actions
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ["3.10"]

    name: Python ${{ matrix.python-version }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: false
          activate-environment: lume-epics
          environment-file: environment.yml
          channels: conda-forge,defaults
          channel-priority: strict
          python-version: ${{ matrix.python-version }}
      - name: Build package
        shell: bash -l {0}
        run: |
          conda install conda-build
          conda build -q conda-recipe --python=${{ matrix.python-version }} --output-folder bld-dir
