
name: Build docs

on:
  push:
    branches:
      - master
      - github-actions
jobs:
  build:
    if: ${{ github.repository == 'slaclab/lume-epics' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    name:  Build docs
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,anaconda
          channel-priority: strict
      - name: Build package
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda install --file requirements.txt
          conda install --file dev-requirements.txt
          conda install --file docs-requirements.txt
          mkdocs build
          mkdocs gh-deploy --force
